// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-Rk5_2oxO385MFX-X1c7vjTJB6r0UgKk',
    appId: '1:805539391390:web:e188cdc526a6e5d946188f',
    messagingSenderId: '805539391390',
    projectId: 'class-work12',
    authDomain: 'class-work12.firebaseapp.com',
    storageBucket: 'class-work12.firebasestorage.app',
    measurementId: 'G-52TL55TTLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYlS4fLfnFgIdk3dA-TfuH6VrMQqtxeCw',
    appId: '1:805539391390:android:0ef585f117fabe7c46188f',
    messagingSenderId: '805539391390',
    projectId: 'class-work12',
    storageBucket: 'class-work12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjO2jYo31PUhoZDzWio2k-RBy_c2TaBGU',
    appId: '1:805539391390:ios:b6c80ca5a026677846188f',
    messagingSenderId: '805539391390',
    projectId: 'class-work12',
    storageBucket: 'class-work12.firebasestorage.app',
    iosBundleId: 'com.example.testclassWork12Mob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjO2jYo31PUhoZDzWio2k-RBy_c2TaBGU',
    appId: '1:805539391390:ios:b6c80ca5a026677846188f',
    messagingSenderId: '805539391390',
    projectId: 'class-work12',
    storageBucket: 'class-work12.firebasestorage.app',
    iosBundleId: 'com.example.testclassWork12Mob',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-Rk5_2oxO385MFX-X1c7vjTJB6r0UgKk',
    appId: '1:805539391390:web:a26b827d8c8cc9cb46188f',
    messagingSenderId: '805539391390',
    projectId: 'class-work12',
    authDomain: 'class-work12.firebaseapp.com',
    storageBucket: 'class-work12.firebasestorage.app',
    measurementId: 'G-78LB7C970T',
  );
}
